env_name: 'bpush'
exp_id : 'try'
other: ''

player: 2
field: 10
grid_observation: False

alg: 'MAAC'
n_episodes: 50000
episode_length: 50
test_n_episodes: 100


lbf:
  max_food: 3
  force_coop: False
  max_player_level: 2
  keep_food: True
  attr_mapping: {'agent': 0, 'id': 1, 'food': 2}

bpush:
  penalty: 0.01
  sensor_range: 4
  attr_mapping: {'agent': 0, 'boulder': 1, 'goal': 2, 'id': 3}

wolfpack:
  max_food_num: 2
  obs_type: 'grid'
  attr_mapping: {'wolf': 0, 'sheep': 1, 'id': 2}

marc:
  dense: False
  relational_embedding : False
  background_id : 'b0'
  abs_id: 'None'

norm_rews : True
batch_size : 1024
seeds: [4001]
buffer_length: 100000
