env_id: 'lbf_6x6_2p_1f_coop'
exp_id : 'try'

player: 2
field: 6


max_food: 1
force_coop: True
dense: false
keep_food: false

#num_colours: 2
#fixed: False
#goal_length: 2
#simple: False
#deterministic: False
#single: False

grid_observation: True
batch_size : 1024
n_episodes: 100000
episode_length: 25
test_n_episodes: 10
test_episode_length: 25
seeds: [4001]
agent_alg: 'rmac'
buffer_length: 10000

#save_interval: 500


