env_id: 'Boxworld_box'
simple: False
deterministic: False
single: False

player: 2
field: 5
num_colours: 2
goal_length: 2
grid_observation: True

n_episodes: 20000
episode_length: 100
test_n_episodes: 5
test_episode_length: 20
seeds: [4001]

agent_alg: 'RMAC'
exp_id : 'std'
batch_size : 64
#save_interval: 500


