env_id: 'lbf_8x8_2p_2f_coop'
exp_id : 'std'

player: 2
field: 8

max_food: 2
force_coop: True

#num_colours: 2
#fixed: False
#goal_length: 2
#simple: False
#deterministic: False
#single: False

grid_observation: True
#batch_size : 128
n_episodes: 5600000
episode_length: 25
test_n_episodes: 10
test_episode_length: 25
seeds: [4001]
agent_alg: 'rmac'
buffer_length: 10000

#save_interval: 500


