#env_id: 'lbf_10x10_4p_4f_coop'
env: 'lbf'
exp_id : 'std'
other: ''

player: 4
field: 10
max_food: 4
force_coop: True
max_player_level: 2

dense: True
simple: False
keep_food: True
norm_rews : True

#num_colours: 2
#fixed: False
#goal_length: 2
#deterministic: False
#single: False

grid_observation: True
batch_size : 1024
n_episodes: 5600000
episode_length: 50
test_n_episodes: 10
test_episode_length: 50
seeds: [4001]
agent_alg: 'rmac'
#buffer_length: 10000



