env_name: 'gridworld'
exp_id : 'std'
other: ''

player: 4
field: 10
grid_observation: False

alg: 'MAAC'
n_episodes: 550000
episode_length: 50
test_n_episodes: 100
#tau: 0.01
device: 'cuda:0'


lbf:
  max_food: 4
  force_coop: True
  max_player_level: 2
  keep_food: True
  attr_mapping: {'agent': 0, 'id': 1, 'food': 2}

bpush:
  penalty: 0.01
  sensor_range: 4
  attr_mapping: {'agent': 0, 'boulder': 1, 'goal': 2, 'id': 3}

wolfpack:
  max_food_num: 2
  obs_type: 'grid'
  sparse: True
  close_penalty : 0.0
  attr_mapping: {'wolf': 0, 'sheep': 1, 'id': 2}

marc:
  dense: False
  relational_embedding : False
  background_id : 'b3'
  abs_id: 'None'
  buffer_length: 100000

maac:
  attend_heads: 4
  buffer_length: 1000000

norm_rews : True
batch_size : 1024
seeds: [4001]
