env_name: 'pp'
exp_id : 'try'
other: ''

player: 2
field: 10
grid_observation: True

alg: 'MARC'
n_episodes: 2500000
episode_length: 50
test_n_episodes: 10
#tau: 0.01
device: 'cuda:0'

pp:
  n_picker: 1
  n_objects: 2
  attr_mapping: {'agent': 0,
                 'objects': 1,
                 'goals': 2,
                 'id':3,
                 'carrying':4,
                 'picker':5,}
lbf:
  max_food: 2
  force_coop: False
  max_player_level: 2
  keep_food: False
  attr_mapping: {'agent': 0, 'id': 1, 'food': 2}

bpush:
  penalty: 0.01
  sensor_range: 4
  attr_mapping: {'agent': 0, 'boulder': 1, 'goal': 2, 'id': 3}

wolfpack:
  max_food_num: 2
  obs_type: 'grid'
  sparse: True
  close_penalty : 0.0
  attr_mapping: {'wolf': 0, 'sheep': 1, 'id': 2}

marc:
  dense: True
  relational_embedding : False
  background_id : 'b0'
  abs_id: 'None'
  buffer_length: 100000
  graph_layer: 'RGAT'

maac:
  attend_heads: 4
  buffer_length: 1000000

norm_rews : True
batch_size : 1024
seeds: [4001]
