env_name: 'lbf'
exp_id : 'std'
other: ''

player: 5
field: 10
grid_observation: True

alg: 'MARC'
n_episodes: 500000
episode_length: 50
test_n_episodes: 10
#tau: 0.01
device: 'cuda'

pp:
  n_picker: 2
  n_objects: 3
  version: 'v3'
  attr_mapping: {'agent': 0,
                 'objects': 1,
                 'goals': 2,
                 'id': 3,
                 'carrying': 4,
                 'picker': 5,}

rware:
  size: 'tiny'
  difficulty: 'easy-'
  attr_mapping: {
    'shelves':0,
    'requests':1,
    'agents':2,
    'goals':3,
    'accessible':4,
#    'agent_load':5,
#    'agent_direction':6,
  }

lbf:
  max_food: 4
  force_coop: True
  max_player_level: 2
  keep_food: True
  attr_mapping: {'agent': 0, 'id': 1, 'food': 2}

bpush:
  penalty: 0.01
  sensor_range: 4
  attr_mapping: {'agent': 0, 'boulder': 1, 'goal': 2, 'id': 3}

wolfpack:
  max_food_num: 2
  obs_type: 'grid'
  sparse: True
  close_penalty : 0.0
  attr_mapping: {'wolf': 0, 'sheep': 1, 'id': 2}

marc:
  dense: True
  relational_embedding : False
  background_id : 'b0'
  abs_id: 'None'
  buffer_length: 1000000
  graph_layer: 'RGCN'
  net_code: '1g1i1f'
maac:
  attend_heads: 1
  buffer_length: 1000000
  hard: True

norm_rews : True
batch_size : 1024
seeds: [4001]
